using System.Collections.Generic;
using Inventory.Domain.Entities;

namespace Inventory.Shared.Utils
{
    public static class OuiLookup
    {
        // Common OUI mappings for manufacturer detection
        private static readonly Dictionary<string, string> OuiMapping = new Dictionary<string, string>
        {
            {"00:00:0C", "Cisco Systems"},
            {"00:01:42", "Cisco Systems"},
            {"00:05:9A", "Cisco Systems"},
            {"00:0A:41", "Cisco Systems"},
            {"00:0D:65", "Cisco Systems"},
            {"00:11:21", "Cisco Systems"},
            {"00:1A:A1", "Cisco Systems"},
            {"00:1B:67", "Cisco Systems"},
            {"00:1C:0E", "Cisco Systems"},
            {"00:1D:70", "Cisco Systems"},
            {"00:1E:14", "Cisco Systems"},
            {"00:1F:6C", "Cisco Systems"},
            {"00:22:55", "Cisco Systems"},
            {"00:23:04", "Cisco Systems"},
            {"00:24:50", "Cisco Systems"},
            {"00:25:45", "Cisco Systems"},
            {"00:26:0A", "Cisco Systems"},
            {"00:26:CA", "Cisco Systems"},
            {"00:50:56", "VMware"},
            {"00:0C:29", "VMware"},
            {"00:05:69", "VMware"},
            {"00:1C:14", "VMware"},
            {"08:00:27", "Oracle VirtualBox"},
            {"52:54:00", "QEMU/KVM"},
            {"00:16:3E", "Xen"},
            {"00:15:5D", "Microsoft Hyper-V"},
            {"00:03:FF", "Microsoft"},
            {"00:12:5A", "Microsoft"},
            {"00:17:FA", "Microsoft"},
            {"00:21:70", "Microsoft"},
            {"00:25:AE", "Microsoft"},
            {"7C:1E:B3", "Microsoft"},
            {"00:11:24", "Apple"},
            {"00:14:51", "Apple"},
            {"00:16:CB", "Apple"},
            {"00:17:F2", "Apple"},
            {"00:19:E3", "Apple"},
            {"00:1B:63", "Apple"},
            {"00:1C:B3", "Apple"},
            {"00:1D:4F", "Apple"},
            {"00:1E:52", "Apple"},
            {"00:1E:C2", "Apple"},
            {"00:1F:5B", "Apple"},
            {"00:1F:F3", "Apple"},
            {"00:21:E9", "Apple"},
            {"00:22:41", "Apple"},
            {"00:23:12", "Apple"},
            {"00:23:DF", "Apple"},
            {"00:24:36", "Apple"},
            {"00:25:00", "Apple"},
            {"00:25:4B", "Apple"},
            {"00:25:BC", "Apple"},
            {"00:26:08", "Apple"},
            {"00:26:4A", "Apple"},
            {"00:26:B0", "Apple"},
            {"00:26:BB", "Apple"},
            {"04:0C:CE", "Apple"},
            {"04:15:52", "Apple"},
            {"04:1E:64", "Apple"},
            {"04:54:53", "Apple"},
            {"04:69:F8", "Apple"},
            {"04:DB:56", "Apple"},
            {"04:E5:36", "Apple"},
            {"08:6D:41", "Apple"},
            {"0C:3E:9F", "Apple"},
            {"0C:4D:E9", "Apple"},
            {"0C:74:C2", "Apple"},
            {"10:9A:DD", "Apple"},
            {"10:DD:B1", "Apple"},
            {"14:10:9F", "Apple"},
            {"14:20:5E", "Apple"},
            {"14:5A:05", "Apple"},
            {"14:7D:DA", "Apple"},
            {"14:BD:61", "Apple"},
            {"18:34:51", "Apple"},
            {"18:65:90", "Apple"},
            {"18:AF:61", "Apple"},
            {"18:E7:F4", "Apple"},
            {"1C:1A:C0", "Apple"},
            {"1C:36:BB", "Apple"},
            {"1C:AB:A7", "Apple"},
            {"20:3C:AE", "Apple"},
            {"20:A2:E4", "Apple"},
            {"20:C9:D0", "Apple"},
            {"24:A0:74", "Apple"},
            {"24:AB:81", "Apple"},
            {"28:37:37", "Apple"},
            {"28:5A:EB", "Apple"},
            {"28:A0:2B", "Apple"},
            {"28:CF:DA", "Apple"},
            {"28:CF:E9", "Apple"},
            {"28:E0:2C", "Apple"},
            {"28:E7:CF", "Apple"},
            {"2C:1F:23", "Apple"},
            {"2C:33:11", "Apple"},
            {"2C:36:F8", "Apple"},
            {"2C:54:91", "Apple"},
            {"2C:B4:3A", "Apple"},
            {"2C:BE:08", "Apple"},
            {"30:10:B3", "Apple"},
            {"30:35:AD", "Apple"},
            {"30:63:6B", "Apple"},
            {"30:90:AB", "Apple"},
            {"30:D9:D9", "Apple"},
            {"34:15:9E", "Apple"},
            {"34:36:3B", "Apple"},
            {"34:A3:95", "Apple"},
            {"34:C0:59", "Apple"},
            {"34:E2:FD", "Apple"},
            {"38:0F:4A", "Apple"},
            {"38:48:4C", "Apple"},
            {"38:89:DC", "Apple"},
            {"3C:07:54", "Apple"},
            {"3C:15:C2", "Apple"},
            {"3C:2E:F9", "Apple"},
            {"40:33:1A", "Apple"},
            {"40:3C:FC", "Apple"},
            {"40:6C:8F", "Apple"},
            {"40:A6:D9", "Apple"},
            {"40:B3:95", "Apple"},
            {"40:CB:C0", "Apple"},
            {"44:00:10", "Apple"},
            {"44:4C:0C", "Apple"},
            {"44:D8:84", "Apple"},
            {"48:43:7C", "Apple"},
            {"48:60:BC", "Apple"},
            {"48:74:6E", "Apple"},
            {"48:A1:95", "Apple"},
            {"48:BF:6B", "Apple"},
            {"4C:32:75", "Apple"},
            {"4C:57:CA", "Apple"},
            {"4C:74:03", "Apple"},
            {"4C:8D:79", "Apple"},
            {"50:32:37", "Apple"},
            {"50:ED:3C", "Apple"},
            {"54:72:4F", "Apple"},
            {"54:AE:27", "Apple"},
            {"54:E4:3A", "Apple"},
            {"58:55:CA", "Apple"},
            {"5C:59:48", "Apple"},
            {"5C:95:AE", "Apple"},
            {"5C:F9:38", "Apple"},
            {"60:33:4B", "Apple"},
            {"60:C5:47", "Apple"},
            {"60:FB:42", "Apple"},
            {"64:20:0C", "Apple"},
            {"64:76:BA", "Apple"},
            {"64:A3:CB", "Apple"},
            {"64:B9:E8", "Apple"},
            {"68:5B:35", "Apple"},
            {"68:96:7B", "Apple"},
            {"68:AB:1E", "Apple"},
            {"68:D9:3C", "Apple"},
            {"6C:40:08", "Apple"},
            {"6C:72:20", "Apple"},
            {"6C:94:66", "Apple"},
            {"6C:AD:F8", "Apple"},
            {"70:11:24", "Apple"},
            {"70:56:81", "Apple"},
            {"70:73:CB", "Apple"},
            {"70:CD:60", "Apple"},
            {"70:DE:E2", "Apple"},
            {"74:E1:B6", "Apple"},
            {"74:E2:E6", "Apple"},
            {"78:31:C1", "Apple"},
            {"78:4F:43", "Apple"},
            {"78:CA:39", "Apple"},
            {"7C:6D:62", "Apple"},
            {"7C:C3:A1", "Apple"},
            {"7C:D1:C3", "Apple"},
            {"80:92:9F", "Apple"},
            {"80:E6:50", "Apple"},
            {"84:38:35", "Apple"},
            {"84:FC:FE", "Apple"},
            {"88:1F:A1", "Apple"},
            {"88:63:DF", "Apple"},
            {"8C:29:37", "Apple"},
            {"8C:2D:AA", "Apple"},
            {"8C:7C:92", "Apple"},
            {"8C:85:90", "Apple"},
            {"90:84:0D", "Apple"},
            {"90:FD:61", "Apple"},
            {"94:E9:79", "Apple"},
            {"98:01:A7", "Apple"},
            {"98:B8:E3", "Apple"},
            {"9C:04:EB", "Apple"},
            {"9C:20:7B", "Apple"},
            {"9C:35:EB", "Apple"},
            {"9C:FC:E8", "Apple"},
            {"A0:99:9B", "Apple"},
            {"A0:CE:C8", "Apple"},
            {"A4:B1:97", "Apple"},
            {"A4:D1:8C", "Apple"},
            {"A8:20:66", "Apple"},
            {"A8:51:AB", "Apple"},
            {"A8:60:B6", "Apple"},
            {"A8:66:7F", "Apple"},
            {"A8:96:75", "Apple"},
            {"AC:3C:0B", "Apple"},
            {"AC:7F:3E", "Apple"},
            {"AC:87:A3", "Apple"},
            {"B0:34:95", "Apple"},
            {"B0:65:BD", "Apple"},
            {"B4:18:D1", "Apple"},
            {"B4:9C:DF", "Apple"},
            {"B8:09:8A", "Apple"},
            {"B8:17:C2", "Apple"},
            {"B8:53:AC", "Apple"},
            {"B8:63:BC", "Apple"},
            {"B8:78:26", "Apple"},
            {"B8:8D:12", "Apple"},
            {"B8:C7:5D", "Apple"},
            {"B8:F6:B1", "Apple"},
            {"BC:52:B7", "Apple"},
            {"BC:6C:21", "Apple"},
            {"BC:93:42", "Apple"},
            {"C0:9A:D0", "Apple"},
            {"C4:2C:03", "Apple"},
            {"C8:2A:14", "Apple"},
            {"C8:33:4B", "Apple"},
            {"C8:B5:B7", "Apple"},
            {"CC:08:8D", "Apple"},
            {"CC:25:EF", "Apple"},
            {"CC:29:F5", "Apple"},
            {"D0:23:DB", "Apple"},
            {"D0:81:7A", "Apple"},
            {"D4:90:9C", "Apple"},
            {"D4:9A:20", "Apple"},
            {"D8:30:62", "Apple"},
            {"D8:8F:76", "Apple"},
            {"D8:96:95", "Apple"},
            {"D8:A2:5E", "Apple"},
            {"DC:37:45", "Apple"},
            {"DC:56:E7", "Apple"},
            {"DC:86:D8", "Apple"},
            {"DC:A9:04", "Apple"},
            {"E0:AC:CB", "Apple"},
            {"E0:B9:BA", "Apple"},
            {"E0:F8:47", "Apple"},
            {"E4:25:E7", "Apple"},
            {"E4:8B:7F", "Apple"},
            {"E4:C6:3D", "Apple"},
            {"E8:80:2E", "Apple"},
            {"E8:B2:AC", "Apple"},
            {"EC:35:86", "Apple"},
            {"F0:18:98", "Apple"},
            {"F0:24:75", "Apple"},
            {"F0:99:BF", "Apple"},
            {"F0:B4:79", "Apple"},
            {"F0:D1:A9", "Apple"},
            {"F4:0F:24", "Apple"},
            {"F4:37:B7", "Apple"},
            {"F4:5C:89", "Apple"},
            {"F8:1E:DF", "Apple"},
            {"F8:27:93", "Apple"},
            {"F8:DB:7F", "Apple"},
            {"FC:25:3F", "Apple"},
            {"FC:E9:98", "Apple"},
            {"00:01:29", "Hewlett-Packard"},
            {"00:01:E6", "Hewlett-Packard"},
            {"00:01:E7", "Hewlett-Packard"},
            {"00:04:EA", "Hewlett-Packard"},
            {"00:08:02", "Hewlett-Packard"},
            {"00:08:C7", "Hewlett-Packard"},
            {"00:0B:CD", "Hewlett-Packard"},
            {"00:0D:9D", "Hewlett-Packard"},
            {"00:0E:7F", "Hewlett-Packard"},
            {"00:0F:20", "Hewlett-Packard"},
            {"00:0F:61", "Hewlett-Packard"},
            {"00:10:E3", "Hewlett-Packard"},
            {"00:11:0A", "Hewlett-Packard"},
            {"00:11:85", "Hewlett-Packard"},
            {"00:12:79", "Hewlett-Packard"},
            {"00:13:21", "Hewlett-Packard"},
            {"00:14:38", "Hewlett-Packard"},
            {"00:14:C2", "Hewlett-Packard"},
            {"00:15:60", "Hewlett-Packard"},
            {"00:16:35", "Hewlett-Packard"},
            {"00:16:B9", "Hewlett-Packard"},
            {"00:17:08", "Hewlett-Packard"},
            {"00:17:A4", "Hewlett-Packard"},
            {"00:18:FE", "Hewlett-Packard"},
            {"00:19:BB", "Hewlett-Packard"},
            {"00:1A:4B", "Hewlett-Packard"},
            {"00:1B:78", "Hewlett-Packard"},
            {"00:1C:C4", "Hewlett-Packard"},
            {"00:1D:31", "Hewlett-Packard"},
            {"00:1E:0B", "Hewlett-Packard"},
            {"00:1F:29", "Hewlett-Packard"},
            {"00:21:F7", "Hewlett-Packard"},
            {"00:22:64", "Hewlett-Packard"},
            {"00:23:7D", "Hewlett-Packard"},
            {"00:24:81", "Hewlett-Packard"},
            {"00:25:B3", "Hewlett-Packard"},
            {"00:26:55", "Hewlett-Packard"},
            {"00:30:6E", "Hewlett-Packard"},
            {"00:60:B0", "Hewlett-Packard"},
            {"00:80:A0", "Hewlett-Packard"},
            {"00:9C:02", "Hewlett-Packard"},
            {"00:A0:D1", "Hewlett-Packard"},
            {"00:BB:CD", "Hewlett-Packard"},
            {"00:C0:EE", "Hewlett-Packard"},
            {"00:E0:81", "Hewlett-Packard"},
            {"00:FD:45", "Hewlett-Packard"},
            {"00:04:75", "Dell"},
            {"00:08:74", "Dell"},
            {"00:0B:DB", "Dell"},
            {"00:0D:56", "Dell"},
            {"00:0F:1F", "Dell"},
            {"00:11:43", "Dell"},
            {"00:12:3F", "Dell"},
            {"00:13:72", "Dell"},
            {"00:14:22", "Dell"},
            {"00:15:C5", "Dell"},
            {"00:16:F0", "Dell"},
            {"00:18:8B", "Dell"},
            {"00:19:B9", "Dell"},
            {"00:1A:A0", "Dell"},
            {"00:1C:23", "Dell"},
            {"00:1D:09", "Dell"},
            {"00:1E:4F", "Dell"},
            {"00:1F:C6", "Dell"},
            {"00:21:9B", "Dell"},
            {"00:22:19", "Dell"},
            {"00:23:AE", "Dell"},
            {"00:24:E8", "Dell"},
            {"00:26:B9", "Dell"},
            {"04:7D:7B", "Dell"},
            {"08:00:69", "Dell"},
            {"0C:C4:7A", "Dell"},
            {"10:98:36", "Dell"},
            {"14:FE:B5", "Dell"},
            {"18:03:73", "Dell"},
            {"18:A9:05", "Dell"},
            {"18:FB:7B", "Dell"},
            {"1C:40:24", "Dell"},
            {"20:47:47", "Dell"},
            {"24:B6:FD", "Dell"},
            {"28:F1:0E", "Dell"},
            {"2C:76:8A", "Dell"},
            {"34:17:EB", "Dell"},
            {"34:E6:D7", "Dell"},
            {"44:A8:42", "Dell"},
            {"4C:76:25", "Dell"},
            {"50:9A:4C", "Dell"},
            {"54:48:10", "Dell"},
            {"5C:F9:DD", "Dell"},
            {"78:45:C4", "Dell"},
            {"84:2B:2B", "Dell"},
            {"84:8F:69", "Dell"},
            {"90:B1:1C", "Dell"},
            {"A4:1F:72", "Dell"},
            {"A4:BA:DB", "Dell"},
            {"B0:83:FE", "Dell"},
            {"B8:2A:72", "Dell"},
            {"B8:CA:3A", "Dell"},
            {"C8:1F:66", "Dell"},
            {"D0:67:E5", "Dell"},
            {"D4:AE:52", "Dell"},
            {"D4:BE:D9", "Dell"},
            {"E0:DB:55", "Dell"},
            {"EC:F4:BB", "Dell"},
            {"F0:1F:AF", "Dell"},
            {"F0:4D:A2", "Dell"},
            {"F8:BC:12", "Dell"},
            {"F8:DB:88", "Dell"},
            {"FC:15:B4", "Dell"},
            {"00:04:76", "3Com"},
            {"00:10:5A", "3Com"},
            {"00:50:DA", "3Com"},
            {"00:60:08", "3Com"},
            {"00:60:97", "3Com"},
            {"00:A0:24", "3Com"},
            {"00:C0:4F", "3Com"},
            {"00:E0:63", "3Com"},
            {"08:00:17", "NSC"},
            {"AA:00:04", "DEC"},
            {"00:00:F8", "DEC"},
            {"00:05:02", "DEC"},
            {"00:20:AF", "3Com"},
            // Intel Corporate OUI entries
            {"00:03:47", "Intel Corporate"},
            {"00:07:E9", "Intel Corporate"},
            {"00:0E:0C", "Intel Corporate"},
            {"00:13:02", "Intel Corporate"},
            {"00:13:20", "Intel Corporate"},
            {"00:15:17", "Intel Corporate"},
            {"00:16:76", "Intel Corporate"},
            {"00:19:D1", "Intel Corporate"},
            {"00:1B:21", "Intel Corporate"},
            {"00:1E:67", "Intel Corporate"},
            {"00:21:6A", "Intel Corporate"},
            {"00:22:FB", "Intel Corporate"},
            {"00:24:D7", "Intel Corporate"},
            {"00:26:C6", "Intel Corporate"},
            {"00:27:0E", "Intel Corporate"},
            {"3C:97:0E", "Intel Corporate"},
            {"40:A8:F0", "Intel Corporate"},
            {"44:85:00", "Intel Corporate"},
            {"4C:79:6E", "Intel Corporate"},
            {"68:05:CA", "Intel Corporate"},
            {"7C:7A:91", "Intel Corporate"},
            {"84:A9:3E", "Intel Corporate"},
            {"A0:A8:CD", "Intel Corporate"},
            {"B4:96:91", "Intel Corporate"},
            {"D0:50:99", "Intel Corporate"},
            {"E4:A4:71", "Intel Corporate"},
            {"F0:92:1C", "Intel Corporate"},
            {"F4:8E:38", "Intel Corporate"},
            // ASUSTek COMPUTER INC. OUI entries
            {"00:0E:A6", "ASUSTek COMPUTER INC."},
            {"00:11:2F", "ASUSTek COMPUTER INC."},
            {"00:13:D4", "ASUSTek COMPUTER INC."},
            {"00:15:F2", "ASUSTek COMPUTER INC."},
            {"00:17:31", "ASUSTek COMPUTER INC."},
            {"00:18:F3", "ASUSTek COMPUTER INC."},
            {"00:1A:92", "ASUSTek COMPUTER INC."},
            {"00:1B:FC", "ASUSTek COMPUTER INC."},
            {"00:1D:60", "ASUSTek COMPUTER INC."},
            {"00:1E:8C", "ASUSTek COMPUTER INC."},
            {"00:22:15", "ASUSTek COMPUTER INC."},
            {"00:23:54", "ASUSTek COMPUTER INC."},
            {"00:24:8C", "ASUSTek COMPUTER INC."},
            {"00:26:18", "ASUSTek COMPUTER INC."},
            {"04:92:26", "ASUSTek COMPUTER INC."},
            {"08:60:6E", "ASUSTek COMPUTER INC."},
            {"0C:9D:92", "ASUSTek COMPUTER INC."},
            {"10:7B:44", "ASUSTek COMPUTER INC."},
            {"14:DD:A9", "ASUSTek COMPUTER INC."},
            {"1C:87:2C", "ASUSTek COMPUTER INC."},
            {"20:CF:30", "ASUSTek COMPUTER INC."},
            {"2C:56:DC", "ASUSTek COMPUTER INC."},
            {"30:5A:3A", "ASUSTek COMPUTER INC."},
            {"38:D5:47", "ASUSTek COMPUTER INC."},
            {"40:16:7E", "ASUSTek COMPUTER INC."},
            {"50:46:5D", "ASUSTek COMPUTER INC."},
            {"54:04:A6", "ASUSTek COMPUTER INC."},
            {"60:45:CB", "ASUSTek COMPUTER INC."},
            {"6C:62:6D", "ASUSTek COMPUTER INC."},
            {"70:4D:7B", "ASUSTek COMPUTER INC."},
            {"74:D0:2B", "ASUSTek COMPUTER INC."},
            {"88:D7:F6", "ASUSTek COMPUTER INC."},
            {"9C:5A:44", "ASUSTek COMPUTER INC."},
            {"AC:22:0B", "ASUSTek COMPUTER INC."},
            {"B0:6E:BF", "ASUSTek COMPUTER INC."},
            {"BC:EE:7B", "ASUSTek COMPUTER INC."},
            {"C8:60:00", "ASUSTek COMPUTER INC."},
            {"D0:17:C2", "ASUSTek COMPUTER INC."},
            {"E0:3F:49", "ASUSTek COMPUTER INC."},
            {"F4:6D:04", "ASUSTek COMPUTER INC."},
            // Fortinet, Inc. OUI entries
            {"00:09:0F", "Fortinet, Inc."},
            {"00:26:0B", "Fortinet, Inc."},
            {"04:BD:88", "Fortinet, Inc."},
            {"08:5B:0E", "Fortinet, Inc."},
            {"0C:A4:02", "Fortinet, Inc."},
            {"24:15:96", "Fortinet, Inc."},
            {"40:A6:E8", "Fortinet, Inc."},
            {"48:0F:CF", "Fortinet, Inc."},
            {"70:4C:A5", "Fortinet, Inc."},
            {"90:6C:AC", "Fortinet, Inc."},
            {"B4:E9:B0", "Fortinet, Inc."},
            // Belkin International Inc. OUI entries
            {"00:0A:75", "Belkin International Inc."},
            {"00:11:50", "Belkin International Inc."},
            {"00:17:3F", "Belkin International Inc."},
            {"00:1C:DF", "Belkin International Inc."},
            {"08:86:3B", "Belkin International Inc."},
            {"14:91:82", "Belkin International Inc."},
            {"94:44:52", "Belkin International Inc."},
            {"B4:75:0E", "Belkin International Inc."},
            {"EC:1A:59", "Belkin International Inc."},
            // Chongqing Fugui Electronics Co., Ltd. OUI entries
            {"00:22:58", "Chongqing Fugui Electronics Co., Ltd."},
            {"2C:AB:A4", "Chongqing Fugui Electronics Co., Ltd."},
            {"F8:1A:67", "Chongqing Fugui Electronics Co., Ltd."}
        };

        public static string? GetManufacturer(string macAddress)
        {
            if (string.IsNullOrEmpty(macAddress))
                return null;

            // Extract the first 8 characters (first 3 octets) from MAC address
            var oui = macAddress.Replace(":", "").Replace("-", "").ToUpper();
            if (oui.Length >= 6)
            {
                var ouiKey = $"{oui.Substring(0, 2)}:{oui.Substring(2, 2)}:{oui.Substring(4, 2)}";
                
                if (OuiMapping.TryGetValue(ouiKey, out var manufacturer))
                {
                    return manufacturer;
                }
            }

            return "Unknown";
        }

        public static DeviceType GuessDeviceType(string macAddress, string? manufacturer, bool hasAgent = false)
        {
            if (string.IsNullOrEmpty(macAddress))
                return DeviceType.Unknown;

            // If agent is installed, it's definitely a computer (desktop/laptop - treat as Desktop)
            if (hasAgent)
                return DeviceType.Desktop;

            var manufacturerLower = manufacturer?.ToLower() ?? "";

            // Network equipment manufacturers
            if (manufacturerLower.Contains("cisco") || 
                manufacturerLower.Contains("fortinet"))
            {
                // Cisco and Fortinet make switches, routers, and other network equipment
                return DeviceType.NetworkDevice;
            }

            // Computer manufacturers (without agent = likely discovered via network)
            if (manufacturerLower.Contains("intel") || 
                manufacturerLower.Contains("asus") || 
                manufacturerLower.Contains("apple") || 
                manufacturerLower.Contains("dell") || 
                manufacturerLower.Contains("microsoft"))
            {
                return DeviceType.Desktop; // Network discovered computers
            }

            // Virtual machine manufacturers
            if (manufacturerLower.Contains("vmware") || 
                manufacturerLower.Contains("virtualbox") ||
                manufacturerLower.Contains("qemu") ||
                manufacturerLower.Contains("hyper-v"))
            {
                return DeviceType.Server; // Virtual machines
            }

            // Printer manufacturers
            if (manufacturerLower.Contains("hp") || 
                manufacturerLower.Contains("hewlett") ||
                manufacturerLower.Contains("canon") ||
                manufacturerLower.Contains("epson"))
            {
                return DeviceType.Printer;
            }

            // Router/Access Point manufacturers
            if (manufacturerLower.Contains("belkin") || 
                manufacturerLower.Contains("netgear") ||
                manufacturerLower.Contains("linksys") ||
                manufacturerLower.Contains("d-link"))
            {
                return DeviceType.Router;
            }

            // Camera manufacturers (including Chinese manufacturers)
            if (manufacturerLower.Contains("hikvision") || 
                manufacturerLower.Contains("dahua") ||
                manufacturerLower.Contains("chongqing fugui") ||
                manufacturerLower.Contains("axis"))
            {
                return DeviceType.Camera;
            }

            // Phone manufacturers
            if (manufacturerLower.Contains("polycom") || 
                manufacturerLower.Contains("avaya") ||
                manufacturerLower.Contains("yealink"))
            {
                return DeviceType.IPPhone;
            }

            return DeviceType.Unknown;
        }
    }
}