// <auto-generated />
using System;
using Inventory.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inventory.Data.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20250813050604_AddBarcodeAndNotesToDevice")]
    partial class AddBarcodeAndNotesToDevice
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Inventory.Domain.Entities.ChangeLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChangeDate");

                    b.HasIndex("DeviceId");

                    b.ToTable("ChangeLogs");
                });

            modelBuilder.Entity("Inventory.Domain.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AgentInstalled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BarcodeNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiscoveryMethod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("MacAddress")
                        .HasMaxLength(17)
                        .HasColumnType("TEXT");

                    b.Property<int>("ManagementType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BarcodeNumber");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IpAddress");

                    b.HasIndex("LastSeen");

                    b.HasIndex("LastUpdate");

                    b.HasIndex("MacAddress");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Inventory.Domain.Entities.NetworkScanHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DevicesFound")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("NetworkRange")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PortScanType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScanTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScanType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("NetworkRange");

                    b.HasIndex("ScanTime");

                    b.HasIndex("Status");

                    b.ToTable("NetworkScanHistories");
                });

            modelBuilder.Entity("Inventory.Domain.Entities.PredefinedNetworkRange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastScanTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NetworkRange")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PortScanType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("ScanCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsActive");

                    b.HasIndex("LastScanTime");

                    b.HasIndex("Name");

                    b.HasIndex("NetworkRange");

                    b.ToTable("PredefinedNetworkRanges");
                });

            modelBuilder.Entity("Inventory.Domain.Entities.SystemUpdate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("CanAutoInstall")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentVersion")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("KBNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastChecked")
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestVersion")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresRestart")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityBulletinId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double?>("SizeInMB")
                        .HasColumnType("REAL");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdateType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DetectedDate");

                    b.HasIndex("DeviceId");

                    b.HasIndex("Priority");

                    b.HasIndex("Status");

                    b.ToTable("SystemUpdates");
                });

            modelBuilder.Entity("Inventory.Domain.Entities.ChangeLog", b =>
                {
                    b.HasOne("Inventory.Domain.Entities.Device", null)
                        .WithMany("ChangeLogs")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Inventory.Domain.Entities.Device", b =>
                {
                    b.OwnsOne("Inventory.Domain.Entities.DeviceHardwareInfo", "HardwareInfo", b1 =>
                        {
                            b1.Property<Guid>("DeviceId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("BiosManufacturer")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<string>("BiosSerial")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<string>("BiosVersion")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Cpu")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<int>("CpuClockMHz")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("CpuCores")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("CpuLogical")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("DiskGB")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Motherboard")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<string>("MotherboardSerial")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<int>("RamGB")
                                .HasColumnType("INTEGER");

                            b1.HasKey("DeviceId");

                            b1.ToTable("Devices");

                            b1.WithOwner()
                                .HasForeignKey("DeviceId");

                            b1.OwnsMany("Inventory.Domain.Entities.DiskInfo", "Disks", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("INTEGER");

                                    b2.Property<Guid>("DeviceHardwareInfoDeviceId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("DeviceId")
                                        .HasMaxLength(200)
                                        .HasColumnType("TEXT");

                                    b2.Property<double>("FreeGB")
                                        .HasColumnType("REAL");

                                    b2.Property<double>("TotalGB")
                                        .HasColumnType("REAL");

                                    b2.HasKey("Id");

                                    b2.HasIndex("DeviceHardwareInfoDeviceId");

                                    b2.ToTable("DiskInfo");

                                    b2.WithOwner()
                                        .HasForeignKey("DeviceHardwareInfoDeviceId");
                                });

                            b1.OwnsMany("Inventory.Domain.Entities.GpuInfo", "Gpus", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("INTEGER");

                                    b2.Property<Guid>("DeviceHardwareInfoDeviceId")
                                        .HasColumnType("TEXT");

                                    b2.Property<float?>("MemoryGB")
                                        .HasColumnType("REAL");

                                    b2.Property<string>("Name")
                                        .HasMaxLength(200)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("Id");

                                    b2.HasIndex("DeviceHardwareInfoDeviceId");

                                    b2.ToTable("GpuInfo");

                                    b2.WithOwner()
                                        .HasForeignKey("DeviceHardwareInfoDeviceId");
                                });

                            b1.OwnsMany("Inventory.Domain.Entities.NetworkAdapter", "NetworkAdapters", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Description")
                                        .HasMaxLength(200)
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid>("DeviceHardwareInfoDeviceId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("IpAddress")
                                        .HasMaxLength(15)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("MacAddress")
                                        .HasMaxLength(17)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("Id");

                                    b2.HasIndex("DeviceHardwareInfoDeviceId");

                                    b2.ToTable("NetworkAdapter");

                                    b2.WithOwner()
                                        .HasForeignKey("DeviceHardwareInfoDeviceId");
                                });

                            b1.OwnsMany("Inventory.Domain.Entities.RamModule", "RamModules", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("INTEGER");

                                    b2.Property<double>("CapacityGB")
                                        .HasColumnType("REAL");

                                    b2.Property<Guid>("DeviceHardwareInfoDeviceId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Manufacturer")
                                        .HasMaxLength(100)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("PartNumber")
                                        .HasMaxLength(100)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("SerialNumber")
                                        .HasMaxLength(100)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Slot")
                                        .HasMaxLength(50)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("SpeedMHz")
                                        .HasMaxLength(50)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("Id");

                                    b2.HasIndex("DeviceHardwareInfoDeviceId");

                                    b2.ToTable("RamModule");

                                    b2.WithOwner()
                                        .HasForeignKey("DeviceHardwareInfoDeviceId");
                                });

                            b1.Navigation("Disks");

                            b1.Navigation("Gpus");

                            b1.Navigation("NetworkAdapters");

                            b1.Navigation("RamModules");
                        });

                    b.OwnsOne("Inventory.Domain.Entities.DeviceSoftwareInfo", "SoftwareInfo", b1 =>
                        {
                            b1.Property<Guid>("DeviceId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ActiveUser")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<string>("InstalledApps")
                                .HasColumnType("TEXT");

                            b1.Property<string>("OperatingSystem")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<string>("OsArchitecture")
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.Property<string>("OsVersion")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<string>("RegisteredUser")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<string>("SerialNumber")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Updates")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Users")
                                .HasColumnType("TEXT");

                            b1.HasKey("DeviceId");

                            b1.ToTable("Devices");

                            b1.WithOwner()
                                .HasForeignKey("DeviceId");
                        });

                    b.Navigation("HardwareInfo");

                    b.Navigation("SoftwareInfo");
                });

            modelBuilder.Entity("Inventory.Domain.Entities.SystemUpdate", b =>
                {
                    b.HasOne("Inventory.Domain.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Inventory.Domain.Entities.Device", b =>
                {
                    b.Navigation("ChangeLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
